_BASE_: "../detectron2/configs/COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml"
MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  BACKBONE:
    NAME: "build_resnet_fpn_backbone"
  ROI_HEADS:
    NUM_CLASSES: 1  # Only one class (Corn Kernel)
  RPN:
    IN_FEATURES: ["p3", "p4", "p5", "p6"]
  ANCHOR_GENERATOR:
    SIZES: [ [ 64 ], [ 128 ], [ 256 ], [ 512 ] ]
DATASETS:
  TRAIN: ("corn_kernels_train",)
  TEST: ("corn_kernels_val",)
SOLVER:
  IMS_PER_BATCH: 2
  BASE_LR: 0.0025
  STEPS: (5000, 8000)
  MAX_ITER: 10000