MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  BACKBONE:
    NAME: "build_resnet_fpn_backbone"
    FREEZE_AT: 2  # Match pre-trained model structure

  RESNETS:
    DEPTH: 50  # Use ResNet-50 (ensure same as training)
    OUT_FEATURES: ["res2", "res3", "res4", "res5"]

  FPN:
    IN_FEATURES: ["res2", "res3", "res4", "res5"]
    OUT_CHANNELS: 256
    FUSE_TYPE: "sum"

  ANCHOR_GENERATOR:
    NAME: "DefaultAnchorGenerator"
    SIZES: [[32], [64], [128], [256]]
    ASPECT_RATIOS: [[0.5, 1.0, 2.0]]
    ANGLES: [[-90, 0, 90]]

  RPN:
    IN_FEATURES: ["p2", "p3", "p4", "p5"]
    BATCH_SIZE_PER_IMAGE: 256
    POSITIVE_FRACTION: 0.5
    NMS_THRESH: 0.7

  ROI_HEADS:
    NAME: "StandardROIHeads"
    IN_FEATURES: ["p4"]  # Ensure only one level is used
    NUM_CLASSES: 1

  MASK_ON: True  # ✅ Enable mask prediction instead of defining MASK_HEAD

  PIXEL_MEAN: [103.53, 116.28, 123.675]  # Ensure 3-channel input
  PIXEL_STD: [1.0, 1.0, 1.0]

SOLVER:
  BASE_LR: 0.002
  MAX_ITER: 5000
  IMS_PER_BATCH: 2
  STEPS: (3000, 4000)
  CHECKPOINT_PERIOD: 500
